#%RAML 1.0 NamedExample
value:
 -
   Name: Shrikant
   UserID: 123
   Email: abc@gmail.com
   Address: Keli
   City: Washim
   PIN: 444503
 -
  Name: Prashant
  UserID: 456
  Email: wer@gmail.com
  Address: Keli
  City : Pune
  PIN: 444333
